"""Point-cloud disk formats kept out of the HTTP boundary."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np

from storage_utils import atomic_write_via_temp
from numpy.typing import ArrayLike, NDArray


def _finite_points_and_colors(
    xyz: ArrayLike, rgba: ArrayLike | None
) -> tuple[NDArray[np.float32], NDArray[np.uint8] | None]:
    points = np.asarray(xyz).reshape(-1, 3)
    mask = np.all(np.isfinite(points), axis=1)
    finite = points[mask].astype(np.float32, copy=False)
    if rgba is None:
        return finite, None
    colors = np.asarray(rgba).reshape(-1, np.asarray(rgba).shape[-1])[mask, :3]
    return finite, colors.astype(np.uint8, copy=False)


def write_ply(path: Path, xyz: ArrayLike, rgba: ArrayLike | None = None, *, binary: bool = True) -> int:
    points, colors = _finite_points_and_colors(xyz, rgba)
    path.parent.mkdir(parents=True, exist_ok=True)
    color_header = ""
    if colors is not None:
        color_header = (
            "property uchar red\nproperty uchar green\nproperty uchar blue\n"
        )
    encoding = "binary_little_endian" if binary else "ascii"
    header = (
        "ply\n"
        f"format {encoding} 1.0\n"
        "comment generated by kuka-zivid-rhino bridge\n"
        f"element vertex {len(points)}\n"
        "property float x\nproperty float y\nproperty float z\n"
        f"{color_header}end_header\n"
    )
    def _write(target: Path) -> None:
        if binary:
            with target.open("wb") as stream:
                stream.write(header.encode("ascii"))
                if colors is None:
                    points.astype("<f4", copy=False).tofile(stream)
                else:
                    dtype = np.dtype(
                        [("x", "<f4"), ("y", "<f4"), ("z", "<f4"), ("r", "u1"), ("g", "u1"), ("b", "u1")]
                    )
                    records = np.empty(len(points), dtype=dtype)
                    records["x"], records["y"], records["z"] = points.T
                    records["r"], records["g"], records["b"] = colors.T
                    records.tofile(stream)
        else:
            with target.open("w", encoding="ascii", newline="\n") as stream:
                stream.write(header)
                if colors is None:
                    np.savetxt(stream, points, fmt="%.6f %.6f %.6f")
                else:
                    combined = np.column_stack([points, colors])
                    np.savetxt(stream, combined, fmt="%.6f %.6f %.6f %d %d %d")

    atomic_write_via_temp(path, _write)
    return len(points)


def write_preview_xyz(path: Path, xyz: ArrayLike, target_count: int) -> int:
    points = np.asarray(xyz).reshape(-1, 3)
    points = points[np.all(np.isfinite(points), axis=1)]
    if target_count <= 0:
        raise ValueError("preview target_count must be positive")
    if len(points) > target_count:
        indices = np.linspace(0, len(points) - 1, num=target_count, dtype=np.int64)
        points = points[indices]
    def _write(target: Path) -> None:
        np.savetxt(target, points, fmt="%.6f %.6f %.6f")

    atomic_write_via_temp(path, _write)
    return len(points)
