__version__: 27
Settings:
    Acquisitions:
        - Acquisition:
              Aperture: __not_set__
              Brightness: __not_set__
              ExposureTime: __not_set__
              Gain: __not_set__
    Color:
        __version__: 9
        Settings2D:
            Acquisitions:
                - Acquisition:
                      Aperture: __not_set__
                      Brightness: __not_set__
                      ExposureTime: __not_set__
                      Gain: __not_set__
            Diagnostics:
                Enabled: __not_set__
