__version__: 27
Settings:
    Acquisitions:
        - Acquisition:
              Aperture: 8.0
              Brightness: 1.0
              ExposureTime: 5000
              Gain: 1.0
    Color:
        __version__: 9
        Settings2D:
            Acquisitions:
                - Acquisition:
                      Aperture: 8.0
                      Brightness: 1.0
                      ExposureTime: 5000
                      Gain: 1.0
            Diagnostics:
                Enabled: false
